# Generated by Django 3.1.7 on 2021-03-05 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_dong_code', models.CharField(help_text='법정동코드', max_length=10)),
                ('city_state_name', models.CharField(help_text='시도명', max_length=40)),
                ('city_gungu_name', models.CharField(help_text='시군구명', max_length=40)),
                ('legal_upmeundong_name', models.CharField(help_text='법정읍면동명', max_length=40)),
                ('legal_lee_name', models.CharField(help_text='법정리명', max_length=40)),
                ('is_mountain', models.BooleanField(help_text='산여부 (0:대지, 1:산)')),
                ('jibun_bonbun_bunji', models.IntegerField(help_text='지번본번(번지)', max_length=4)),
                ('jibun_boobun_ho', models.IntegerField(help_text='지번부번(호)', max_length=4)),
                ('road_name_code', models.CharField(help_text='도로명코드 (시군구코드(5) + 도로명번호(7))', max_length=12)),
                ('road_name', models.CharField(help_text='도로명', max_length=80)),
                ('is_underground', models.CharField(help_text='지하여부 (0:지상, 1:지하, 2:공중)', max_length=1)),
                ('building_bonbun', models.IntegerField(help_text='건물본번', max_length=5)),
                ('building_boobun', models.IntegerField(help_text='건물부번', max_length=5)),
                ('construction_document_building_name', models.CharField(help_text='건축물대장 건물명', max_length=40)),
                ('detail_building_name', models.CharField(help_text='상세건물명', max_length=100)),
                ('building_management_no', models.CharField(help_text='건물관리번호', max_length=25)),
                ('upmeondong_no', models.CharField(help_text='읍면동일련번호', max_length=2)),
                ('administration_dong_no', models.CharField(help_text='행정동일련번호', max_length=2)),
                ('administration_code', models.CharField(help_text='행정동코드', max_length=10)),
                ('administration_name', models.CharField(help_text='행정동명', max_length=40)),
                ('zip_code', models.CharField(help_text='우편번호', max_length=5)),
                ('zip_no', models.CharField(help_text='우편일련번호', max_length=3)),
                ('multi_delievery_address_name', models.CharField(help_text='다량배달처명', max_length=40)),
                ('move_reason_code', models.CharField(help_text='이동사유코드', max_length=2)),
                ('create_time', models.CharField(help_text='고시일자', max_length=8)),
                ('before_road_name_address', models.CharField(help_text='변동전도로명주소', max_length=25)),
                ('city_gungu_building_name', models.CharField(help_text='시군구용 건물명', max_length=40)),
                ('is_multi_building', models.CharField(help_text='공동주택여부', max_length=1)),
                ('base_area_no', models.CharField(help_text='기초구역번호', max_length=5)),
                ('is_detail_address', models.CharField(help_text='상세주소여부', max_length=1)),
                ('empty_one', models.CharField(help_text='비고1', max_length=15)),
                ('empty_two', models.CharField(help_text='비고2', max_length=15)),
            ],
            options={
                'ordering': ['id', 'legal_dong_code'],
            },
        ),
        migrations.CreateModel(
            name='Jibun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_dong_code', models.CharField(help_text='법정동코드', max_length=10)),
                ('city_state_name', models.CharField(help_text='시도명', max_length=40)),
                ('city_gungu_name', models.CharField(help_text='시군구명', max_length=40)),
                ('legal_upmeundong_name', models.CharField(help_text='법정읍면동명', max_length=40)),
                ('legal_lee_name', models.CharField(help_text='법정리명', max_length=40)),
                ('is_mountain', models.BooleanField(help_text='산여부 (0:대지, 1:산)')),
                ('jibun_bonbun_bunji', models.IntegerField(help_text='지번본번(번지)', max_length=4)),
                ('jibun_boobun_ho', models.IntegerField(help_text='지번부번(호)', max_length=4)),
                ('road_name_code', models.CharField(help_text='도로명코드 (시군구코드(5) + 도로명번호(7))', max_length=12)),
                ('is_underground', models.CharField(help_text='지하여부 (0:지상, 1:지하, 2:공중)', max_length=1)),
                ('building_bonbun', models.IntegerField(help_text='건물본번', max_length=5)),
                ('building_boobun', models.IntegerField(help_text='건물부번', max_length=5)),
                ('jibun_no', models.IntegerField(help_text='지번일련번호', max_length=10)),
                ('move_reason_code', models.CharField(help_text='이동사유코드 (31:신규, 34:변동, 63:폐지', max_length=2)),
            ],
            options={
                'ordering': ['id', 'legal_dong_code'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='썸네일')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['author'],
            },
        ),
    ]
