# Generated by Django 3.1.7 on 2021-03-05 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='jibun',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
