# Generated by Django 3.1.7 on 2021-03-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210307_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='jibun_bonbun_bunji',
            field=models.IntegerField(help_text='지번본번(번지)'),
        ),
        migrations.AlterField(
            model_name='building',
            name='jibun_boobun_ho',
            field=models.IntegerField(help_text='지번부번(호)'),
        ),
    ]
